User-agent:  *
Disallow: /wp-admin
Disallow: /wp-admin/admin-ajax.php?action=process_simple_like&post_id=18&nonce=8cac6a54ed&is_comment=0&disabled=true
Disallow: /admin/login
Disallow: /admin/
Disallow: /admin/portfolio
Disallow: /thank-you/
Disallow: /admin/cats/all
Disallow: /admin/products/all
Disallow: /admin/pages
Disallow: /admin/faqs
Disallow: /admin/setting
Disallow: /admin/blog
Disallow: /admin/add-blog
Disallow: /admin/reviews
Disallow: /admin/add-product/
Disallow: /admin/add-cat/
Disallow: /admin/photos/
Disallow: /search?
Disallow: /admin/brands
Disallow: /admin/qoute/
Disallow: /admin/box/
Disallow: /admin/add-box/
Disallow: /admin/newsletters
Disallow: /admin/order_process
Disallow: /admin/how_it_works
Disallow: /admin/contact-forms/
Sitemap: https://enterests.com/sitemap.xml